import { callLLMWithJSON } from './llm';

export type ReasoningStepType = 'intent' | 'decompose' | 'compile';

export interface IntentResult {
  businessGoal: string;
  userType: string;
  productShape: string;
  lifecycle: string;
  ambiguity: string;
  decisionPoints: string[];
}

export interface AtomicTask {
  phase: number;
  phaseLabel: string;
  file: string;
  responsibility: string;
  input: string;
  output: string;
  dependencies: string[];
}

export interface DecomposeResult {
  tasks: AtomicTask[];
  phases: { phase: number; label: string; files: string[] }[];
}

export interface ReasoningStep {
  type: ReasoningStepType;
  label: string;
  result: IntentResult | DecomposeResult | string;
  status: 'done' | 'error';
}

export async function inferIntent(userInput: string): Promise<IntentResult> {
  const system = `你是一位有 10 年经验的产品技术顾问。

分析用户的模糊想法，输出结构化的意图分析：

1. businessGoal — 用户真正想解决的问题
2. userType — 谁会用？自己用、小团队、还是面向公众
3. productShape — Web / Mobile / API / CLI
4. lifecycle — 想法验证期、MVP、增长期
5. ambiguity — 哪些关键信息缺失
6. decisionPoints — 支撑判断的具体线索

输出严格 JSON：{
  "businessGoal": "string",
  "userType": "string",
  "productShape": "string",
  "lifecycle": "string",
  "ambiguity": "string",
  "decisionPoints": ["string"]
}`;

  return await callLLMWithJSON<IntentResult>([
    { role: 'system', content: system },
    { role: 'user', content: userInput },
  ]);
}

export async function decomposeToAtomicTasks(
  intent: IntentResult,
  userInput: string
): Promise<DecomposeResult> {
  const system = `你是一位高级全栈工程师，把产品需求拆解为开发任务。

从基础设施层开始，往上到业务层，最后是 UI 层。
每个文件只做一件事，依赖关系有向无环。
至少 8 个文件任务，3-5 个 Phase。

输出严格 JSON：{
  "tasks": [{
    "phase": 1,
    "phaseLabel": "阶段名称",
    "file": "src/xxx/xxx.ts",
    "responsibility": "核心职责",
    "input": "输入类型",
    "output": "输出类型",
    "dependencies": ["依赖文件"]
  }],
  "phases": [{
    "phase": 1,
    "label": "阶段名称",
    "files": ["文件列表"]
  }]
}`;

  const userMessage = `原始需求：${userInput}

产品意图：
- 业务目标：${intent.businessGoal}
- 目标用户：${intent.userType}
- 产品形态：${intent.productShape}
- 项目阶段：${intent.lifecycle}`;

  return await callLLMWithJSON<DecomposeResult>([
    { role: 'system', content: system },
    { role: 'user', content: userMessage },
  ]);
}

export async function generateChain(
  userInput: string,
  onStep: (step: ReasoningStep) => void
): Promise<{ prompt: string; steps: ReasoningStep[] }> {
  const steps: ReasoningStep[] = [];

  const intent = await inferIntent(userInput);
  const intentStep: ReasoningStep = { type: 'intent', label: '意图识别', result: intent, status: 'done' };
  steps.push(intentStep);
  onStep(intentStep);

  const decompose = await decomposeToAtomicTasks(intent, userInput);
  const decomposeStep: ReasoningStep = { type: 'decompose', label: '任务拆解', result: decompose, status: 'done' };
  steps.push(decomposeStep);
  onStep(decomposeStep);

  const compileStep: ReasoningStep = { type: 'compile', label: '编译', result: '(programmatic)', status: 'done' };
  steps.push(compileStep);
  onStep(compileStep);

  return { prompt: '(generated by route)', steps };
}
