import { Step } from '@/lib/types/execution';

export interface ExecutionReport {
  prompt: string;
  steps: Step[];
  memoriesUsed: any[];
  memoryInfluenced: boolean;
  adaptations: string[];
  executionId: string | null;
  timestamp: Date;
}

export function exportExecutionReport(report: ExecutionReport): string {
  const markdown = `
# AgentForge Execution Report

## Prompt
${report.prompt}

---

## Execution Summary
- **Execution ID**: ${report.executionId || 'N/A'}
- **Date**: ${report.timestamp.toLocaleString()}
- **Total Steps**: ${report.steps.length}
- **Memory Influenced**: ${report.memoryInfluenced ? 'Yes' : 'No'}

---

## Memory Influence
${report.memoriesUsed.length > 0 
  ? `
### Retrieved Memories (${report.memoriesUsed.length})
${report.memoriesUsed.map((memory, i) => `- Memory ${i + 1}`).join('\\n')}

### Adaptations Applied
${report.adaptations.length > 0 
  ? report.adaptations.map(a => `- ${a}`).join('\\n') 
  : '- No specific adaptations applied'}
`
  : 'No relevant memories were retrieved for this execution.'}

---

## Execution Steps
${report.steps.map((step, i) => `
### Step ${i + 1}: ${step.agent}
**Task**: ${step.task}

**Status**: ${step.status}

${step.output ? `**Output**: ${step.output}` : ''}

---
`).join('')}

---

## Generated by AgentForge
Memory-Augmented Adaptive Engineering System

This report was generated from a real execution of the AgentForge AI Engineering Operating System.
`;

  return markdown.trim();
}

export function downloadReport(report: ExecutionReport): void {
  const markdown = exportExecutionReport(report);
  const blob = new Blob([markdown], { type: 'text/markdown' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  const filename = `agentforge-execution-${report.executionId || Date.now()}.md`;
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
